config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "static_pages#home"

  get "/about_us", to: "static_pages#about_us"
  get "/note", to: "static_pages#note"
  get "/note_click", to: "static_pages#note_click"
  get "/line_to_line", to: "static_pages#line_to_line"
  get "/ph_to_ph", to: "static_pages#ph_to_ph"

  resources :words
  resources :articles
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/antonym.rb
class Antonym < ActiveRecord::Base
  belongs_to :antonymWord, class_name: "Word", foreign_key: "word_id"
  belongs_to :antonymMeaning, class_name: "Meaning", foreign_key: "meaning_id"
end

app/models/article.rb
class Article < ActiveRecord::Base
  include RailsAdminArticle

  has_many :word_articles
  has_many :words, through: :word_articles

  validates :vn_title, presence: true
  validates :kh_title, presence: true
  validates :vn_article, presence: true
  validates :kh_article, presence: true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/concerns/rails_admin_word.rb
module RailsAdminWord
  extend ActiveSupport::Concern

  included do
    rails_admin do
      edit do
        field :wordText do
          label "Word"
        end
        field :isIdiom do
          label "Idiom"
        end
        field :isTechnical do
          label "Technical"
        end
        field :meanings
      end
    end
  end
end

app/models/example.rb
class Example < ActiveRecord::Base
  include RailsAdminExample

  belongs_to :meaning

  validates :vn_example, presence: true
  validates :vn_example, presence: true
end

app/models/meaning.rb
class Meaning < ActiveRecord::Base
  include RailsAdminMeaning

  belongs_to :word
  has_many :examples
  has_many :synonyms
  has_many :antonyms
  has_many :synonymWords, through: :synonyms
  has_many :antonymWords, through: :antonyms
  accepts_nested_attributes_for :examples

  validates :meaning, presence: true
  validates :word, presence: false
end

app/models/synonym.rb
class Synonym < ActiveRecord::Base
  belongs_to :synonymWord, class_name: "Word", foreign_key: "word_id"
  belongs_to :synonymMeaning, class_name: "Meaning", foreign_key: "meaning_id"
end

app/models/word.rb
class Word < ActiveRecord::Base
  include RailsAdminWord

  has_many :meanings
  has_many :word_articles
  has_many :articles, through: :word_articles
  has_many :synonyms
  has_many :antonyms
  has_many :synonymMeanings, through: :synonyms
  has_many :antonymMeanings, through: :antonyms
  accepts_nested_attributes_for :meanings, :allow_destroy => true

  validates :wordText, presence: true
  #validates :meanings, presence: true
end

app/models/word_article.rb
class WordArticle < ActiveRecord::Base
  belongs_to :word
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :change_locale

  def change_locale
     if ['en', 'kh', 'vn'].include?(params[:locale])
      cookies[:locale] = params[:locale]
      params.delete :locale
      redirect_to words_url
    end

    I18n.locale = cookies[:locale] || I18n.default_locale
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
    @popular_words = Word.order(searchTime: :desc).take(30)
  end

  def show
    @article = Article.find params[:id]
    @popular_words = Word.order(searchTime: :desc).take(30)
  end
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
end

app/controllers/meanings_controller.rb
class MeaningsController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def about_us
  end

  def home
    @q = Word.ransack(params[:q])
  end

  def note
    word_ids = cookies[:note_words].split(" ").map(&:to_f)
    @words = Word.where(id: word_ids)
  end

  def note_click
    if cookies[:note_words] == nil
      cookies[:note_words] = params[:word_id]
    else
      word_ids = cookies[:note_words].split(" ")
      if word_ids.include? params[:word_id].to_s
        word_ids.delete(params[:word_id].to_s)
      else
        word_ids.push(params[:word_id])
      end
      cookies[:note_words] = word_ids.join(" ")
    end
  end

  def line_to_line
    article = Article.find params[:id]
    vn_article_arr = article.vn_article.split('.')
    kh_article_arr = article.kh_article.split('។')
    @ltl_article = vn_article_arr.zip(kh_article_arr).flatten.compact
  end

  def ph_to_ph
    @article = Article.find params[:id]
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :search_object, :get_top_word

  def show
    @word = Word.find params[:id]
    @word.update_attribute(:searchTime, @word.searchTime + 1)
  end

  def index
    @words = @q.result
  end

  private
  def search_object
    @q = Word.ransack(params[:q])
  end

  def get_top_word
    @popular_words = Word.order(searchTime: :desc).take(30)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t("titles.title")
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  def set_lang
    case cookies[:locale]
    when 'vn'
      t "selects.langs.vn"
    when 'kh'
      t "selects.langs.kh"
    else
      t "selects.langs.en"
    end
  end

  def set_note_word_color
    if cookies[:note_words] == nil
      "material-icons grey-text"
    else
      word_ids = cookies[:note_words].split(" ")
      if word_ids.include? @word.id.to_s
        "material-icons yellow-text"
      else
        "material-icons grey-text"
      end
    end
  end

  def is_noted? word
    if cookies[:note_words] == nil
      return false
    else
      word_ids = cookies[:note_words].split(" ")
      word_ids.include? word.id.to_s
    end
  end

  def is_vn_lang?
    cookies[:locale] == "vn" ? true : false
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/meanings_helper.rb
module MeaningsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/articles/_article.html.erb
<div class="card grey lighten-4">
  <div class="card-content black-text">
    <%= link_to article_path(article) do %>
      <span class="card-title">
        <%= is_vn_lang? ? article.vn_title : article.kh_title %>
      </span>
    <% end %>
    <p>
      <%= is_vn_lang? ? article.vn_article.html_safe : article.kh_article.html_safe %>
    </p>
  </div>
  <div class="card-action">
    <%= link_to t("label.read_more") + " >>", article_path(article) %>
  </div>
</div>

app/views/articles/index.html.erb
<div class="row">
  <div class="col s8">
    <%= render @articles %>
  </div>
  <div class="col s4">
    <%=  render "shared/lang" %>
    <%= render "shared/top_30" %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="row article">
  <div class="col s8">
    <div class="word-title blue-text">
      <%= @article.vn_title %><br>
      <%= @article.kh_title %>
    </div>
    <%= link_to ph_to_ph_path(id: params[:id]), remote: true do %>
      <i class="Medium material-icons orange-text">view_agenda</i>
    <% end %>
    <%= link_to line_to_line_path(id: params[:id]), remote: true do %>
      <i class="Medium material-icons orange-text">subject</i>
    <% end %>
    <div id="content-article" >
      <div class="vn-article">
        <div class="chip">
          <img src="/assets/vn.png" alt="Contact Person">
          <%= t "label.langs.vn_lang" %>
        </div>
        <%= @article.vn_article.html_safe %>
      </div>

      <div class="kh-article">
        <div class="chip">
          <img src="/assets/kh.png" alt="Contact Person">
          <%= t "label.langs.kh_lang" %>
        </div>
        <%= @article.kh_article.html_safe %>
      </div>
    </div>
    <% if !@article.words.blank? %>
      <div class="relate-word">
        <span class=" new badge blue delete-margin-left" data-badge-caption="<%= t 'label.related_word' %>">
          <%= @article.words.count %>
        </span>
        &nbsp;&nbsp;
        <%= render @article.words %>
      </div>
    <% end %>
  </div>

  <div class="col s4">
    <%=  render "shared/lang" %>
    <%= render "shared/top_30" %>
  </div>
</div>

app/views/examples/_example.html.erb
<div class="example">
  - <%= example.vn_example %><br />
  - <%= example.kh_example %><br />
  <img src="/assets/computer.jpg" alt="Smiley face" class="materialboxed"
    data-caption="<%= example.vn_example %>">
</div>

app/views/meanings/_meaning.html.erb
<div class="margin-left-meaning">
  <div class="meaning-title"><i class="tiny material-icons  pink-text">room</i><%= meaning.meaning %></div>
  <% if meaning.isIdiom %>
    <span class="delete-margin-left new badge red left" data-badge-caption="">
      <%= t "label.idiom_word" %>
    </span><br/>
  <% end %>
  <% antonym = meaning.antonymWords %>
  <% synonym = meaning.synonymWords %>
  <% if !antonym.blank? %>
    <%= render partial: "shared/antonym", object: antonym %>
  <% end %>
  <% if !synonym.blank? %>
   <%= render partial: "shared/synonym", object: synonym %>
  <% end %>
  <div class="margin-left-example">
    <% if !meaning.examples.blank? %>
      <%= t "label.example" %>
      <div class="margin-left-example-title">
        <%= render meaning.examples %>
      </div>
    <% end %>
  </div>
</div>

app/views/words/_word.html.erb
<div class="show-word">
  <%= link_to word.wordText, word_path(word) %>
  <% if params[:action] != "show" %>
    <% if word.isIdiom %>
      <i class="font-size-icon-note Tiny material-icons red-text">stop</i>
    <% end %>
    <% if word.isTechnical %>
      <i class="font-size-icon-note Tiny material-icons green-text">stop</i>
    <% end %>
    <% if !(params[:action] == "note") && is_noted?(word) %>
      <i class="font-size-icon-note Tiny material-icons yellow-text">stop</i>
    <% end %>
  <% else %>
    ,&nbsp;
  <% end %>
</div>

app/views/words/index.html.erb
<div class="row">
  <div class="col s8">
    <% if @words.any? %>
      <%= render @words %>
    <% else %>
      <%= t "alerts.no_result" %>
    <% end %>
  </div>
  <div class="col s4">
    <%= render "shared/lang" %>
    <%= render "shared/top_30" %>
  </div>
</div>

app/views/words/show.html.erb
<% provide :title, @word.wordText %>
<div class="row word">
  <div class="col s8">
    <div class="row">
      <div class="col s10">
        <div class="blue-text text-darken-2 word-title">
          <%= @word.wordText %><br/>
          <%= render "shared/chips_technical" %>
          <%= render "shared/chips_idiom" %>
        </div>
      </div>
      <div class="col s2">
        <%= link_to note_click_path(word_id: @word.id), remote: true do %>
          <i data-wordId= <%= @word.id %> class="<%= set_note_word_color %>" id="remember-word" title="<%= t "titles.note" %>">star</i>
        <% end %>
        <%= link_to note_path do %>
          <i class="material-icons" id="list-remember-word"​​ title="<%= t "titles.remember_word" %>">library_books</i>
        <% end %>
      </div>
    </div>
    <%= render @word.meanings %>
    <%= render @word.meanings.example %>
  </div>
  <div class="col s4">
    <%=  render "shared/lang" %>
    <%= render "shared/top_30" %>
  </div>
</div>