config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "static_pages#home"

  get "/about_us", to: "static_pages#about_us"
  get "/note", to: "static_pages#note"
  get "/note_click", to: "static_pages#note_click"
  get "/line_to_line", to: "static_pages#line_to_line"
  get "/ph_to_ph", to: "static_pages#ph_to_ph"

  resources :words
  resources :articles
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/antonym.rb
class Antonym < ActiveRecord::Base
  belongs_to :antonymWord, class_name: "Word", foreign_key: "word_id"
  belongs_to :antonymMeaning, class_name: "Meaning", foreign_key: "meaning_id"
end

app/models/article.rb
class Article < ActiveRecord::Base
  include RailsAdminArticle

  has_many :word_articles
  has_many :words, through: :word_articles

  validates :vn_title, presence: true
  validates :kh_title, presence: true
  validates :vn_article, presence: true
  validates :kh_article, presence: true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/example.rb
class Example < ActiveRecord::Base
  include RailsAdminExample

  belongs_to :meaning

  validates :vn_example, presence: true
  validates :vn_example, presence: true
end

app/models/meaning.rb
class Meaning < ActiveRecord::Base
  include RailsAdminMeaning

  belongs_to :word
  has_many :examples
  has_many :synonyms
  has_many :antonyms
  has_many :synonymWords, through: :synonyms
  has_many :antonymWords, through: :antonyms
  accepts_nested_attributes_for :examples

  validates :meaning, presence: true
  validates :word, presence: false
end

app/models/synonym.rb
class Synonym < ActiveRecord::Base
  belongs_to :synonymWord, class_name: "Word", foreign_key: "word_id"
  belongs_to :synonymMeaning, class_name: "Meaning", foreign_key: "meaning_id"
end

app/models/word.rb
class Word < ActiveRecord::Base
  include RailsAdminWord

  has_many :meanings
  has_many :word_articles
  has_many :articles, through: :word_articles
  has_many :synonyms
  has_many :antonyms
  has_many :synonymMeanings, through: :synonyms
  has_many :antonymMeanings, through: :antonyms
  accepts_nested_attributes_for :meanings, :allow_destroy => true

  validates :wordText, presence: true
  #validates :meanings, presence: true
end

app/models/word_article.rb
class WordArticle < ActiveRecord::Base
  belongs_to :word
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :change_locale

  def change_locale
     if ['en', 'kh', 'vn'].include?(params[:locale])
      cookies[:locale] = params[:locale]
      params.delete :locale
      redirect_to words_url
    end

    I18n.locale = cookies[:locale] || I18n.default_locale
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
    @popular_words = Word.order(searchTime: :desc).take(30)
  end

  def show
    @article = Article.find params[:id]
    @popular_words = Word.order(searchTime: :desc).take(30)
  end
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
end

app/controllers/meanings_controller.rb
class MeaningsController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def about_us
  end

  def home
    @q = Word.ransack(params[:q])
  end

  def note
    word_ids = cookies[:note_words].split(" ").map(&:to_f)
    @words = Word.where(id: word_ids)
  end

  def note_click
    if cookies[:note_words] == nil
      cookies[:note_words] = params[:word_id]
    else
      word_ids = cookies[:note_words].split(" ")
      if word_ids.include? params[:word_id].to_s
        word_ids.delete(params[:word_id].to_s)
      else
        word_ids.push(params[:word_id])
      end
      cookies[:note_words] = word_ids.join(" ")
    end
  end

  def line_to_line
    article = Article.find params[:id]
    vn_article_arr = article.vn_article.split('.')
    kh_article_arr = article.kh_article.split('។')
    @ltl_article = vn_article_arr.zip(kh_article_arr).flatten.compact
  end

  def ph_to_ph
    @article = Article.find params[:id]
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :search_object, :get_top_word

  def show
    @word = Word.find params[:id]
    @word.update_attribute(:searchTime, @word.searchTime + 1)
  end

  def index
    @words = @q.result
  end

  private
  def search_object
    @q = Word.ransack(params[:q])
  end

  def get_top_word
    @popular_words = Word.order(searchTime: :desc).take(30)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t("titles.title")
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  def set_lang
    case cookies[:locale]
    when 'vn'
      t "selects.langs.vn"
    when 'kh'
      t "selects.langs.kh"
    else
      t "selects.langs.en"
    end
  end

  def set_note_word_color
    if cookies[:note_words] == nil
      "material-icons grey-text"
    else
      word_ids = cookies[:note_words].split(" ")
      if word_ids.include? @word.id.to_s
        "material-icons yellow-text"
      else
        "material-icons grey-text"
      end
    end
  end

  def is_noted? word
    if cookies[:note_words] == nil
      return false
    else
      word_ids = cookies[:note_words].split(" ")
      word_ids.include? word.id.to_s
    end
  end

  def is_vn_lang?
    cookies[:locale] == "vn" ? true : false
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/meanings_helper.rb
module MeaningsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <meta name="keywords" content="">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body>
    <div id="wrapper">
      <div class="content container grey lighten-5">
        <%= render "shared/flash" %>
        <%= render "shared/header" %>
        <div class="container">
          <% if params[:controller] == "words" %>
            <%= render "shared/search" %>
          <% end %>
          <%= yield %>
        </div>
        <%= render "shared/footer" %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_antonym.html.erb
<%= t("label.antonym") %>
<span class="antonym-synonym-inline"><%= render antonym %></span>

app/views/shared/_chips_idiom.html.erb
<% if @word.isIdiom? %>
  <span class="new badge red left" data-badge-caption="">
    <%= t "label.idiom_word" %>
  </span>
<% end %>

app/views/shared/_chips_technical.html.erb
<% if @word.isTechnical %>
  <span class="delete-margin-left new badge green left" data-badge-caption="">
    <%= t "label.technical_word" %>
  </span>
<% end %>

app/views/shared/_flash.html.erb
<div class="col-md-10 col-md-offset-1 width-flash">
<script type="text/javascript">
  <% flash.each do |f| %>
    <% type = f[0].to_s.gsub("alert", "error").gsub("notice", "info").gsub("success", "success") %>
     toastr["<%= type %>"]("<%= f[1] %>");
  <% end %>
</script>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <footer class="page-footer">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Footer Content</h5>
          <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Links</h5>
          <ul>
            <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      © 2014 Copyright Text
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
      </div>
    </div>
  </footer>
</div>

app/views/shared/_header.html.erb
<div class="header">
  <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo"><img src="/assets/app_icon.png" class="app-icon" /></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to t("headers.vk_dic"), words_path %></li>
        <li><%= link_to t("headers.article") , articles_path %></li>
        <li><%= link_to t("headers.about_us") , about_us_path %></li>
      </ul>
    </div>
  </nav>
</div>

app/views/shared/_lang.html.erb
<label><%= t "titles.lang" %></label>
<select class="icons" onchange="javascript:location.href = this.value;">
  <option value="" disabled selected><%= set_lang %></option>
  <option value="/words?locale=kh" data-icon="/assets/kh.png" class="circle"><%= t "selects.langs.kh" %></option>
  <option value="/words?locale=vn" data-icon="/assets/vn.png" class="circle"><%= t "selects.langs.vn" %></option>
  <option value="/words?locale=en" data-icon="/assets/en.png" class="circle"><%= t "selects.langs.en" %></option>
</select>

app/views/shared/_line_to_line_article.html.erb
<div class="line-to-line-text">
  <% @ltl_article.each do |text| %>
    <%= text %><br>
  <% end %>
</div>

app/views/shared/_ph_to_ph.html.erb
<div class="vn-article">
  <div class="chip">
    <img src="/assets/vn.png" alt="Contact Person">
    <%= t "label.langs.vn_lang" %>
  </div>
  <%= @article.vn_article.html_safe %>
</div>
<div class="kh-article">
  <div class="chip">
    <img src="/assets/kh.png" alt="Contact Person">
    <%= t "label.langs.kh_lang" %>
  </div>
  <%= @article.kh_article.html_safe %>
</div>

app/views/shared/_popular_word.html.erb
<div class="blue-text">
  <%= link_to popular_word.wordText, word_path(popular_word) %>
</div>

app/views/shared/_search.html.erb
<h4><%= t "headers.vk_dic" %></h4>
<div class="search-bar">
  <%= search_form_for @q do |f| %>
    <div class="file-field input-field">
      <button class="btn waves-effect waves-light" type="submit" name="action">
        <%= t "buttons.search" %>
        <i class="material-icons right">search</i>
      </button>
      <div class="file-path-wrapper">
      <%= f.search_field :wordText_cont, class: "file-path validate", type: "text",
       placeholder: t("placeholders.search_word") %>
       <!-- On screen keyboard -->
       <!--  <%= f.search_field :wordText_cont, class: "file-path validate osk-trigger", type: "text", placeholder: t("placeholders.search_word"), "data-osk-options" => "disableReturn disableTab" %>
        <i class="medium material-icons osk-trigger">subtitles</i> -->
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_synonym.html.erb
<%= t "label.synonym" %>
<span class="antonym-synonym-inline"><%= render synonym %></span>

app/views/shared/_top_30.html.erb
<div class="card-panel cyan lighten-5">
  <%= t "titles.top_30" %>
  <%= render partial: "shared/popular_word", collection: @popular_words  %>
</div>